apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-applications
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: env/prod/app
    repoURL: https://github.com/Navin009/test-argo.git
    targetRevision: HEAD
  project: default