apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: prod-applications
        path: env/prod/argo
        namespace: prod
      - name: uat-applications
        path: env/uat/argo
        namespace: uat
      - name: common-applications
        path: env/common/argo
        namespace: common
  template:
    metadata:
      name: '{{.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/Navin009/test-argo.git
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'