apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-application
spec:
  project: default
  source:
    repoURL: https://github.com/Navin009/test-argo.git
    path: env/common/app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
