apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  project: default
  source:
    repoURL: https://github.com/Navin009/test-argo.git
    path: env/common/kafka
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true