apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-applications
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: env/prod/argo
    repoURL: https://github.com/Navin009/test-argo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false