apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ok
spec:
  generators:
    - list:
        elements:
          - app: common
  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Navin009/test-argo.git
        targetRevision: HEAD
        path: env/common/argo
      destination:
        server: 'https://kubernetes.default.svc'
