apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ok
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - name: prod-applications
          path: prod
        - name: uat-applications
          path: uat
        - name: common-applications
          path: common
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Navin009/test-argo.git
        targetRevision: HEAD
        path: env/'{{path}}'/argo
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
